
#  ______ __           __   ______ __
# |      |  |--.---.-.|  |_|   __ \  |.--.--.-----.
# |   ---|     |  _  ||   _|    __/  ||  |  |__ --|
# |______|__|__|___._||____|___|  |__||_____|_____|
#
#          Advanced chat for beginners
#                   By Wolveh
#

# global options
global:
    # Allow formatting in player's messages and chat
    # note: doesn't affect the output syntax
    # default: true
    enableFormatting: true

    # Require players to have permission for chat and message formatting (chatplus.formatting)
    # default: false
    requireFormattingPermission: false

    # Detect urls in messages/chat
    # default: true
    detectUrls: true


# chat functionality
chat:
    # enable custom chat
    # default: true
    customChatEnabled: true

    # Detect hashtags in chat
    # default: true
    detectHashTags: true

    # Detect player tags in chat
    # default: true
    detectPlayerTags: true

    # this has to be enabled for tooltips, Command executions/suggestions etc.
    # default: true
    enableJson: true

    #Custom chat style

    # variables
    #     %player%         - player name
    #     %displayname%    - player's display name
    #     %message%        - chat message
    #     %prefix%         - player's prefix

    # if json is enabled, the following variables can be used:
    #     %ttp: '<tooltip message>'%      - tooltip
    #     %cmd: '<command>'%              - run a command
    #     %sgt: '<command suggestion>'%   - suggest a command
    #     %url: '<url>'%                  - open a url
    # you can also nest other variables in the json variables

    # all  json variables are assigned to the text block they're in
    # text blocks can be split with '||'

    # example:
    # "%displayname% %ttp: '%player%'% || %message% %cmd: '/msg %player% '%"

    # default: "%player%: %message%"
    chatStyle: "%player%: %message%"