
#  ______ __           __   ______ __
# |      |  |--.---.-.|  |_|   __ \  |.--.--.-----.
# |   ---|     |  _  ||   _|    __/  ||  |  |__ --|
# |______|__|__|___._||____|___|  |__||_____|_____|
#
#          Advanced chat for beginners
#                   By Wolveh
#

# global options
global:
    # Allow chat formatting in player's messages
    # note: doesn't affect the output syntax
    # default: true
    enableFormatting: true

    # Require players to have permission for chat formatting (chat.formatting)
    # default: false
    requireFormattingPermission: false

    # Detect urls in messages (not yet implemented)
    # default: true
    autoDetectUrls: true


# chat functionality
chat:
    # enable custom chat
    # default: false
    customChatEnabled: false

    # this has to be enabled for tooltips, Command executions/suggestions etc.
    # default: true
    enableJson: true

    # output variables:
    #
    # %display-name% - Player's display name e.g. name set by /nick (can sometimes include prefixes, depending on permissions manager/prefix manager)
    # %player-name% - Player's actual name
    # %player-world% - Player's current world
    # %message% - original chat message
    #
    # {json{<string to add json to>||<json component>}} - add json to the message
    #     available json components:
    #     ttp{<String for tooltip>} - tooltip
    #     run{<Command to run>} - make player run a command
    #     sgt{<Command to suggest>} - Suggest a command for the player (insert it into their chat box)
    #     url{<url>} - Add a url
    #     can add multiple json components to the json entry with "||" then the component
    # note: enableJson must be enabled for this to work
    #
    # example:
    #     "{json{%display-name% >>||ttp{%player-name%\n&6&m--+|+--\n&eWorld: &f%player-world%}}} %message%"
    #
    # default: "%player-name%: %message%"
    outputSyntax: "%player-name%: %message%"