
#  ______ __           __   ______ __
# |      |  |--.---.-.|  |_|   __ \  |.--.--.-----.
# |   ---|     |  _  ||   _|    __/  ||  |  |__ --|
# |______|__|__|___._||____|___|  |__||_____|_____|
#
#          Advanced chat for beginners
#                   By Wolveh
#

# global options
global:
    # Allow formatting in player's messages and chat
    # note: doesn't affect the output syntax
    # default: true
    enableFormatting: true

    # Require players to have permission for chat and message formatting (chatplus.formatting)
    # default: false
    requireFormattingPermission: false

    # Detect urls in messages/chat
    # default: true
    detectUrls: true


# chat functionality
chat:
    # enable custom chat
    # default: true
    enableCustomChat: true

    # Detect hashtags in chat
    # default: true
    detectHashTags: true

    # Detect player tags in chat
    # default: true
    detectPlayerTags: true

    # this has to be enabled for tooltips, Command executions/suggestions etc.
    # default: true
    enableJson: true

    #Custom chat style

    # variables
    #     %player%         - player name
    #     %displayname%    - player's display name
    #     %message%        - chat message
    #     %prefix%         - player's prefix

    # if json is enabled, you can add json elements with the following tags:
    #  ttp: <tooltip message>
    #  cmd: <command>
    #  sgt: <command suggestion>
    #  url: <url>
    # all json and text is split with '||'

    # example:
    # "%displayname% || ttp: %player% || %message% || sgt: /msg %player% "
    # default: "%player%: %message%"
    chatStyle: "%player%: %message%"