name: ${name}
main: ${groupId}.${artifactId}.${name}
version: ${version}
author: ${author}

softdepend: [Essentials]

commands:
  message:
    description: Send a message to a player.
    aliases: [msg, m, tell, t, whisper, w, pm]
  reply:
    description: Reply to a player.
    aliases: [r]
  chatplus:
    description: Get help for the plugin.
  socialspy:
    description: Spy on player messages
    permission: chatplus.spy
    aliases: [msgspy, messagespy]

  permissions:
    chatplus.*:
      default: op
      children:
        chatplus.staff:
          default: op
        chatplus.spy:
          default: op
        chatplus.formatting:
          default: op