name: ${name}
main: ${groupId}.${artifactId}.${name}
version: ${version}
author: ${author}
commands:
  message:
    description: Send a message to a player.
    aliases: [msg, m, tell, t, whisper, w, pm]
  reply:
    description: Reply to a player.
    aliases: [r]
  messenger:
    description: Get help for the plugin.
  socialspy:
    description: Spy on player messages
    permission: chatplus.spy
    aliases: [msgspy, messagespy]

  permissions:
    messenger.*:
      default: op
      children:
        messenger.staff:
          default: op
        messenger.spy:
          default: op
        messenger.color:
          default: op