name: Messenger
main: space.wolv.messenger.Messenger
version: 1.0
author: Wolveh
commands:
  message:
    description: Send a message to a player.
    aliases: [msg, m, tell, t, whisper, w, pm]
  reply:
    description: Reply to a player.
    aliases: [r]